#!/usr/bin/zsh
# $1 is the token generated by the proxy server \ 
if [ $1 ]; then
	curl -X GET \
	  -H "Authorization: Bearer $1" \
	  -H "Content-Type: application/json" \
	  'localhost:8080/elasticsearch/software_jobs/_search?q=python'
else
	echo No token specified
fi
